server:
  port: 80
  servlet:
    context-path: /
    session:
      timeout: 300m

    
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:7777/{}
    username: root
    password: 123
    dbcp2:
      initial-size: 5
      max-total: 10
      min-idle: 3  
mybatis:
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  config-location: classpath:mybatis/config/mybatis-config.xml      